import type { Candidate } from "../types.js";

/**
 * Deterministic, no-API-call response that demonstrates the full pipeline
 * end-to-end. Used in two situations:
 *  1. No ANTHROPIC_API_KEY or DEEPSEEK_API_KEY set (zero-cost smoke test)
 *  2. CODE2WIKI_MOCK=1 or --mock flag (CI tests)
 *
 * Output is intentionally marked as a draft so a user never mistakes it
 * for a real LLM result.
 */
export function mockExtract(candidate: Candidate, projectName: string): unknown {
  const titleStem = humanize(candidate.name);
  const isController = candidate.kind === "controller-method";
  const isCfTag = candidate.kind === "cf-tag-function";

  const triggerWord = isController
    ? "A user submits a request to the corresponding endpoint."
    : isCfTag
      ? "A caller invokes this CFML function from the application layer."
      : "A caller invokes this function.";

  return {
    title: `${capitalize(titleStem)} (DRAFT)`,
    actor:
      isController
        ? "A signed-in user (or anonymous visitor, depending on the route)"
        : "An internal application caller",
    summary: `[code2wiki MOCK MODE: no LLM call was made]\n\nThis is a placeholder use case generated by the deterministic mock. To produce real, non-technical documentation, set ANTHROPIC_API_KEY or DEEPSEEK_API_KEY in your environment and re-run \`code2wiki generate\`. The pipeline that produced this draft is the same one that will call the LLM in real mode.`,
    trigger: triggerWord,
    preconditions: [
      `The caller has access to invoke \`${candidate.name}\`.`,
      `The application is running and dependencies are reachable.`,
    ],
    main_flow: [
      {
        step: `The system enters \`${candidate.name}\` in ${candidate.relativePath} (lines ${candidate.lineStart}-${candidate.lineEnd}).`,
        footnote: undefined,
      },
      ...(candidate.hints.callees?.slice(0, 5).map((c) => ({
        step: `The system calls \`${c}\` (raw extraction; LLM would describe this in business terms).`,
        footnote: undefined,
      })) ?? []),
      {
        step: `Control returns to the caller.`,
        footnote: undefined,
      },
    ],
    alternate_flows: [
      {
        label: "Real LLM run pending",
        description:
          "The mock cannot infer alternate flows. Configure ANTHROPIC_API_KEY or DEEPSEEK_API_KEY for the real extraction.",
      },
    ],
    postconditions: [
      "Whatever the function did. Mock cannot tell you.",
    ],
    business_rules: [
      ...(candidate.hints.databaseTables?.length
        ? [
            {
              rule: `Touches database tables: ${candidate.hints.databaseTables.join(", ")} (raw extraction).`,
              footnote: undefined,
            },
          ]
        : []),
      ...(candidate.hints.annotations?.length
        ? [
            {
              rule: `Annotations present: ${candidate.hints.annotations.join(", ")} (raw extraction).`,
              footnote: undefined,
            },
          ]
        : []),
    ],
    test_scenarios: [
      {
        label: "Happy path (mock placeholder)",
        gwt: "Given the function preconditions are met, when it is invoked, then it returns successfully. (Real LLM would generate scenario-specific Given/When/Then here.)",
      },
    ],
    related: [],
    tags: [
      candidate.language,
      candidate.kind,
      isController ? "controller" : "library",
      "mock-output",
    ],
    confidence: "low",
    confidence_reason: `Generated by mock; no LLM call was made. Project: ${projectName}.`,
  };
}

function humanize(name: string): string {
  return name
    .replace(/([A-Z])/g, " $1")
    .replace(/[._]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
