import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";
import {
  bannerHtml,
  bodyForPreview,
  md2html,
  renderConfluenceLookalike,
  renderConfluencePayload,
  renderIndexHtml,
  renderNotionLookalike,
  renderNotionPayload,
  renderNotionRichText,
  wrapConfluencePayload,
} from "./local-wiki-preview.js";
import {
  FENCE_CLOSE,
  FENCE_OPEN_PREFIX,
  type BannerInputs,
} from "../../src/core/publishers/types.js";

const BANNER: BannerInputs = {
  repoName: "demo-repo",
  sourceLink: "https://example.invalid/demo-repo",
  lastSyncedIso: "2026-05-13T17:00:00.000Z",
};

// Representative of real code2wiki use-case output: structured headings,
// bullets, inline code, and an ampersand in prose. Raw HTML-shaped text in
// prose is now safe, markdownToConfluenceStorage escapes unknown tags
// (allowlist: HTML comments + <details>/<summary>). See the regression
// tests in confluence.test.ts.
// Frontmatter is stripped by gray-matter before the body reaches the
// renderer in the real script; tests pass body-only directly.
const SAMPLE_BODY = `# Sample Title

Some intro paragraph with ampersands & angle-quoted "phrases".

## Main flow

- Step one
- Step two with \`code\`

## Notes

A paragraph about user "input" and the system "response".
`;

describe("wrapConfluencePayload", () => {
  it("includes the XML declaration and Atlassian namespace bindings", () => {
    const wrapped = wrapConfluencePayload(
      '<ac:structured-macro ac:name="info"/>',
    );
    expect(wrapped.startsWith("<?xml ")).toBe(true);
    expect(wrapped).toContain('xmlns:ac="http://atlassian.com/content"');
    expect(wrapped).toContain(
      'xmlns:ri="http://atlassian.com/resource/identifier"',
    );
  });

  it("opens and closes the root element exactly once", () => {
    const payload = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const wrapped = wrapConfluencePayload(payload);
    expect(wrapped.match(/<root\b/g)?.length).toBe(1);
    expect(wrapped.match(/<\/root>/g)?.length).toBe(1);
    expect(wrapped.indexOf("<root")).toBeLessThan(wrapped.indexOf("</root>"));
  });

  // Round-trip through xmllint when libxml2 is on PATH. Skips silently on
  // systems without it (e.g. CI containers without xmllint installed).
  // macOS ships libxml2 / xmllint by default.
  it("parses cleanly through xmllint (when available)", () => {
    const probe = spawnSync("xmllint", ["--version"]);
    if (probe.status !== 0) {
      console.log("  (skipped, xmllint not available)");
      return;
    }
    const payload = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const wrapped = wrapConfluencePayload(payload);
    const r = spawnSync("xmllint", ["--noout", "-"], { input: wrapped });
    if (r.status !== 0) {
      throw new Error(
        `xmllint rejected the wrapped output:\n${r.stderr.toString()}`,
      );
    }
  });
});

describe("renderConfluencePayload", () => {
  it("matches the live publisher shape: banner + rendered body, no extra fence", () => {
    const out = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    expect(out).toContain("ac:structured-macro");
    // SAMPLE_BODY has no fence comments, so neither should the output.
    expect(out).not.toContain(FENCE_OPEN_PREFIX);
    expect(out).not.toContain(FENCE_CLOSE);
  });

  it("renders body content after the banner", () => {
    const out = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const bannerIdx = out.indexOf("ac:structured-macro");
    const titleIdx = out.indexOf("Sample Title");
    expect(bannerIdx).toBeGreaterThanOrEqual(0);
    expect(titleIdx).toBeGreaterThan(bannerIdx);
  });

  it("preserves source-side fence comments when the body already has them", () => {
    const bodyWithFence =
      `# Title\n\nContent.\n\n---\n\n` +
      `${FENCE_OPEN_PREFIX} id=demo -->\n` +
      `*Generated by code2wiki.*\n` +
      `${FENCE_CLOSE}\n`;
    const out = renderConfluencePayload(bodyWithFence, BANNER, "sample");
    expect(out).toContain(FENCE_OPEN_PREFIX);
    expect(out).toContain(FENCE_CLOSE);
  });

  it("does not emit em dashes (U+2014) in banner copy", () => {
    const out = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    expect(out).not.toContain("\u2014");
  });

  // Regression: real code2wiki output contains <hr> (from `---` separators
  // in markdown), <h2>, <ul>, etc. Earlier preview wrapper put these inside
  // a <p>, which xmllint rightly rejects. The fix is plain concatenation.
  it("produces XHTML that survives a body containing <hr> and block elements", () => {
    const realisticBody = `# Title

Some prose.

---

## Another section

- item one
- item two
`;
    const probe = spawnSync("xmllint", ["--version"]);
    if (probe.status !== 0) {
      console.log("  (skipped, xmllint not available)");
      return;
    }
    const wrapped = wrapConfluencePayload(
      renderConfluencePayload(realisticBody, BANNER, "regression"),
    );
    const r = spawnSync("xmllint", ["--noout", "-"], { input: wrapped });
    if (r.status !== 0) {
      throw new Error(
        `xmllint rejected the wrapped output containing <hr>:\n` +
          r.stderr.toString(),
      );
    }
  });
});

describe("renderNotionPayload", () => {
  it("returns the banner callout block first", () => {
    const blocks = renderNotionPayload(SAMPLE_BODY, BANNER);
    expect(Array.isArray(blocks)).toBe(true);
    expect(blocks.length).toBeGreaterThan(1);
    const first = blocks[0] as { type?: string };
    expect(first.type).toBe("callout");
  });

  it("serialises to valid JSON", () => {
    const blocks = renderNotionPayload(SAMPLE_BODY, BANNER);
    const json = JSON.stringify(blocks);
    const round = JSON.parse(json);
    expect(Array.isArray(round)).toBe(true);
    expect(round.length).toBe(blocks.length);
  });

  it("does not emit em dashes (U+2014) in banner copy", () => {
    const blocks = renderNotionPayload(SAMPLE_BODY, BANNER);
    expect(JSON.stringify(blocks)).not.toContain("\u2014");
  });
});

describe("bodyForPreview", () => {
  it("strips the managed-fence markers when both are present", () => {
    const fenced = `before${FENCE_OPEN_PREFIX} ts="x" -->INSIDE${FENCE_CLOSE}after`;
    expect(bodyForPreview(fenced)).toBe("INSIDE");
  });

  it("returns the original text when no fence is present", () => {
    expect(bodyForPreview("plain markdown body")).toBe("plain markdown body");
  });
});

describe("md2html", () => {
  it("escapes HTML special characters in text content", () => {
    const html = md2html("plain text with <tag> & ampersand");
    expect(html).toContain("&amp;");
    expect(html).toContain("&lt;tag&gt;");
  });

  it("renders headings, bullets, and inline code", () => {
    const html = md2html("# Title\n\n- one\n- two\n\nCall `foo()`.");
    expect(html).toContain("<h1>Title</h1>");
    expect(html).toContain("<li>one</li>");
    expect(html).toContain("<code>foo()</code>");
  });
});

describe("bannerHtml", () => {
  it("includes the repo name and source link", () => {
    const html = bannerHtml(BANNER);
    expect(html).toContain(BANNER.repoName);
    expect(html).toContain(BANNER.sourceLink);
  });

  it("does not contain em dashes", () => {
    expect(bannerHtml(BANNER)).not.toContain("\u2014");
  });
});

describe("renderConfluenceLookalike", () => {
  it("includes the page title, info macro body, and rendered body", () => {
    const payload = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const html = renderConfluenceLookalike({
      title: "Sample",
      storagePayload: payload,
    });
    expect(html).toContain(
      "<title>Sample (Confluence preview)</title>",
    );
    expect(html).toContain('class="cf-title"');
    // Banner copy lives inside .cf-info.
    expect(html).toContain("cf-info");
    expect(html).toContain("auto-generated by code2wiki");
    // The body should include the first heading from SAMPLE_BODY.
    expect(html).toContain("Sample Title");
  });

  it("does not leak raw fence comments or em dashes into the page", () => {
    const payload = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const html = renderConfluenceLookalike({
      title: "Sample",
      storagePayload: payload,
    });
    // The fence-open prefix string should be stripped from the visible body.
    expect(html).not.toContain(FENCE_OPEN_PREFIX);
    expect(html).not.toContain(FENCE_CLOSE);
    expect(html).not.toContain("\u2014");
  });

  it("escapes the title to defend against XSS via page metadata", () => {
    const payload = renderConfluencePayload(SAMPLE_BODY, BANNER, "sample");
    const html = renderConfluenceLookalike({
      title: '<script>alert("x")</script>',
      storagePayload: payload,
    });
    expect(html).not.toContain('<script>alert("x")</script>');
    expect(html).toContain("&lt;script&gt;");
  });
});

describe("renderNotionRichText", () => {
  it("renders bold and italic annotations", () => {
    const html = renderNotionRichText([
      { type: "text", text: { content: "Hello" }, annotations: { bold: true } },
      { type: "text", text: { content: " world" } },
    ]);
    expect(html).toBe("<strong>Hello</strong> world");
  });

  it("converts inline markdown inside rich_text content", () => {
    const html = renderNotionRichText([
      { type: "text", text: { content: "use `foo()` for **safety**" } },
    ]);
    expect(html).toContain("<code>foo()</code>");
    expect(html).toContain("<strong>safety</strong>");
  });

  it("renders links from text.link.url", () => {
    const html = renderNotionRichText([
      {
        type: "text",
        text: { content: "View source", link: { url: "https://example.com" } },
      },
    ]);
    expect(html).toContain('<a href="https://example.com">View source</a>');
  });
});

describe("renderNotionLookalike", () => {
  it("renders the banner callout, page title, and walks every block type", () => {
    const blocks = renderNotionPayload(SAMPLE_BODY, BANNER);
    const html = renderNotionLookalike({
      title: "Sample",
      blocks: blocks as never,
    });
    expect(html).toContain("<title>Sample (Notion preview)</title>");
    expect(html).toContain('class="nt-title"');
    expect(html).toContain("nt-callout");
    expect(html).toContain("auto-generated by code2wiki");
    // Sample body contains an h1 + h2 + bullets.
    expect(html).toContain("<h2>");
    expect(html).toContain("<ul>");
    expect(html).toContain("<li>");
  });

  it("groups consecutive list items into a single ul/ol", () => {
    const html = renderNotionLookalike({
      title: "x",
      blocks: [
        { type: "bulleted_list_item", bulleted_list_item: { rich_text: [{ type: "text", text: { content: "a" } }] } },
        { type: "bulleted_list_item", bulleted_list_item: { rich_text: [{ type: "text", text: { content: "b" } }] } },
        { type: "paragraph", paragraph: { rich_text: [{ type: "text", text: { content: "x" } }] } },
        { type: "numbered_list_item", numbered_list_item: { rich_text: [{ type: "text", text: { content: "1" } }] } },
      ],
    });
    expect(html.match(/<ul>/g)?.length).toBe(1);
    expect(html.match(/<\/ul>/g)?.length).toBe(1);
    expect(html.match(/<ol>/g)?.length).toBe(1);
    expect(html.match(/<\/ol>/g)?.length).toBe(1);
  });

  it("emits a visible debug marker for unknown block types", () => {
    const html = renderNotionLookalike({
      title: "x",
      blocks: [{ type: "embed" }] as never,
    });
    expect(html).toContain("[unhandled block type: embed]");
  });
});

describe("renderIndexHtml", () => {
  it("groups entries by repo and links Confluence + Notion previews + raw artifacts", () => {
    const html = renderIndexHtml([
      { repo: "wheels", slug: "a", title: "Page A" },
      { repo: "wheels", slug: "b", title: "Page B" },
      { repo: "petclinic", slug: "c", title: "Page C" },
    ]);
    expect(html).toContain("<h2>wheels");
    expect(html).toContain("<h2>petclinic");
    // Confluence preview links
    expect(html).toContain('href="wheels/a/confluence.html"');
    expect(html).toContain('href="petclinic/c/confluence.html"');
    // Notion preview links
    expect(html).toContain('href="wheels/b/notion.html"');
    // Raw artifact links
    expect(html).toContain('href="wheels/a/confluence.xhtml"');
    expect(html).toContain('href="petclinic/c/notion.json"');
  });
});
