#!/usr/bin/env python3
"""Strip em dashes (U+2014, "—") from authored markdown files in this repo.

Enforces the project rule (see CLAUDE.md "Code style"): no em dashes in docs.
Idempotent: re-running on a clean tree is a no-op.

Substitution policy:
- In markdown headers (`^# `, `^## `, ...): ` — ` → `: ` (em dash often plays
  the role of a colon in titles / appositives).
- Elsewhere: ` — ` → `, ` (most common, reads naturally).
- Edge cases (no-space `—`, leading/trailing): conservative `,` fallback.

Out of scope (skipped):
- `examples/*/actual.md` (regenerated by the parser/LLM on every run; the
  prompt rule + the LLM doing the right thing is what keeps these clean).
- `examples/*/source.md` (raw source-code excerpts; not authored prose).
- `examples/*/expected.md` and `examples/*/notes.md` (gold-standard fixtures;
  touching them risks breaking the regression-test snapshot match).
- `references/**` (gitignored clones of CF / Java reference codebases).
- `**/node_modules/**` (vendored deps).
- `.code2wiki/**` (per-customer runtime state, gitignored).

Usage:
  python3 tools/scripts/strip-em-dashes.py            # write changes in place
  python3 tools/scripts/strip-em-dashes.py --check    # report only, exit 1 if any found

Add to CI alongside the existing tests if regressions become a problem.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

EM = "—"

# Resolve repo root: this script lives at tools/scripts/strip-em-dashes.py
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

SKIP_PATH_FRAGMENTS = (
    "/node_modules/",
    "/.code2wiki/",
    "/references/",
    "/examples/",  # all examples/ files are out of scope (see module docstring)
    "/.claude/worktrees/",
    # Bot-self-modification rule (CLAUDE.md, Ocean-bot rule #11): diffs
    # touching tools/ocean-bot/** require dashboard approval. Em-dash
    # discipline inside the bot is therefore enforced via the bot's own
    # CI-red-scrub flow (see prior scrub commits a0de423, 083542c), not
    # by this project linter. Removing this entry without a parallel
    # mechanism for the bot would let any operator running the script
    # bypass the bot-self-mod rule with a 1-char "policy compliance" edit.
    "/tools/ocean-bot/",
    # This scrubber and its test contain the em-dash character by design
    # (match constants + test fixtures); scanning them always self-flags.
    "/tools/scripts/strip-em-dashes.py",
    "/tools/scripts/strip-em-dashes.test.py",
)


def should_skip(p: Path) -> bool:
    # Match against the path RELATIVE to the repo root, never the absolute
    # path. When the repo root itself lives under a skip fragment (a git
    # worktree at ~/code2wiki/.claude/worktrees/<name>/ is the live case),
    # absolute-path matching skips EVERY file and the check passes
    # vacuously ("0 em dashes found across 0 files").
    try:
        rel = p.resolve().relative_to(REPO_ROOT.resolve())
    except ValueError:
        rel = p
    s = "/" + str(rel).replace("\\", "/")
    return any(frag in s for frag in SKIP_PATH_FRAGMENTS)


import re as _re

def _replace_em_in_prose(seg: str, is_header: bool) -> str:
    if is_header:
        new = seg.replace(f" {EM} ", ": ")
        new = new.replace(f"{EM} ", ": ")
        new = new.replace(f" {EM}", ":")
        return new.replace(EM, ":")
    else:
        new = seg.replace(f" {EM} ", ", ")
        new = new.replace(f"{EM} ", ", ")
        new = new.replace(f" {EM}", ",")
        return new.replace(EM, ", ")


def transform(text: str, *, is_markdown: bool = True) -> tuple[str, int]:
    """Return (new_text, count_removed).

    When is_markdown=True (the default), backtick-delimited segments are
    treated as inline code spans and preserved verbatim. This is correct
    for .md files where ``foo`` is non-prose code.

    When is_markdown=False, the entire line is treated as prose. This is
    correct for .ts/.mjs/.cjs/.tsx files where backticks delimit
    TEMPLATE LITERALS that overwhelmingly contain prose (log messages,
    error strings, HTML strings). Without this branch, a regression like
    `console.log(\\\\\\`API down -- check Stripe\\\\\\`)` silently kept the em
    dash because the whole template literal was skipped (see
    autonomous_loop_log.md 2026-05-17 01:23 needs-you for the
    motivating regression in apps/dashboard/src/lib/stripe/checkout.ts).
    """
    lines = text.split("\n")
    new_lines: list[str] = []
    removed = 0
    for line in lines:
        before = line.count(EM)
        # Header detection is a markdown-only concern (`^# heading`). In
        # .ts/.mjs files a leading `#` is either a shebang line or
        # nothing; treat everything as non-header prose there.
        is_header = is_markdown and line.lstrip().startswith("#")
        if is_markdown:
            # Split on inline code spans so em dashes inside backticks
            # are preserved.
            segments = _re.split(r"(`[^`]+`)", line)
            new_segs = []
            for i, seg in enumerate(segments):
                if i % 2 == 1:  # inside backticks
                    new_segs.append(seg)
                else:
                    new_segs.append(_replace_em_in_prose(seg, is_header))
            new = "".join(new_segs)
        else:
            new = _replace_em_in_prose(line, is_header)
        removed += before - new.count(EM)
        new_lines.append(new)
    return "\n".join(new_lines), removed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="report files that would change; exit 1 if any")
    args = parser.parse_args()

    md_files = [
        p
        for pattern in (
            "*.md",
            "*.ts",
            "*.tsx",
            "*.mjs",
            "*.cjs",
            "*.mts",
            "*.cts",
            "*.yml",
            "*.yaml",
            "*.toml",
            "*.sh",
            "*.py",
            "*.example",
            "*.json",
        )
        for p in REPO_ROOT.rglob(pattern)
        if not should_skip(p)
    ]
    total = 0
    touched_files: list[tuple[Path, int]] = []
    for p in md_files:
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        if EM not in text:
            continue
        new, n = transform(text, is_markdown=p.suffix == ".md")
        if n > 0:
            if not args.check:
                p.write_text(new, encoding="utf-8")
            touched_files.append((p, n))
            total += n

    for p, n in touched_files:
        print(f"  {n:>3}  {p.relative_to(REPO_ROOT)}")
    print(f"\n{total} em dashes {'found' if args.check else 'replaced'} "
          f"across {len(touched_files)} files.")

    if args.check and total > 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
