import { describe, expect, it } from "vitest";
import { computeMarkdownSnapshot } from "./snapshot.js";

const SAMPLE = `---
code2wiki_id: demo-v1
title: Demo
slug: demo
status: active
tags:
  - alpha
---

## Summary

A short summary line.

## Actor and triggers

- **Actor:** A visitor
- **Trigger:** Page load

## Postconditions

- Nothing is mutated.

---

<!-- code2wiki:managed:start id=demo-v1 -->
*Generated by code2wiki from commit \`aaaaaaa\` on 2026-05-08T00:00:00Z.*
*Confidence: **high**, clear logic.*
<!-- code2wiki:managed:end -->
`;

describe("computeMarkdownSnapshot", () => {
  it("extracts ordered section titles, sorted frontmatter keys, and a stable body hash", () => {
    const snap = computeMarkdownSnapshot(SAMPLE);
    expect(snap.sections).toEqual([
      "Summary",
      "Actor and triggers",
      "Postconditions",
    ]);
    expect(snap.frontmatterKeys).toEqual([
      "code2wiki_id",
      "slug",
      "status",
      "tags",
      "title",
    ]);
    expect(snap.contentHash).toMatch(/^[0-9a-f]{64}$/);
    expect(snap.managedBlockHash).toMatch(/^[0-9a-f]{64}$/);
    expect(snap.bodyLineCount).toBeGreaterThan(0);
  });

  it("is deterministic across calls", () => {
    const a = computeMarkdownSnapshot(SAMPLE);
    const b = computeMarkdownSnapshot(SAMPLE);
    expect(a).toEqual(b);
  });

  it("ignores managed-fence content when hashing the body; fence churn must not invalidate the snapshot", () => {
    const baseline = computeMarkdownSnapshot(SAMPLE);
    const withChurnedFence = SAMPLE.replace(
      "from commit `aaaaaaa` on 2026-05-08T00:00:00Z",
      "from commit `bbbbbbb` on 2026-09-01T12:34:56Z",
    );
    const churned = computeMarkdownSnapshot(withChurnedFence);
    expect(churned.contentHash).toBe(baseline.contentHash);
    expect(churned.managedBlockHash).not.toBe(baseline.managedBlockHash);
  });

  it("detects body changes via the content hash", () => {
    const edited = SAMPLE.replace("A short summary line.", "An edited line.");
    const baseline = computeMarkdownSnapshot(SAMPLE);
    const after = computeMarkdownSnapshot(edited);
    expect(after.contentHash).not.toBe(baseline.contentHash);
    expect(after.sections).toEqual(baseline.sections);
  });

  it("handles input with no managed fence (degraded but well-defined)", () => {
    const noFence = `---\ntitle: bare\n---\n\n## Only section\n\nbody\n`;
    const snap = computeMarkdownSnapshot(noFence);
    expect(snap.sections).toEqual(["Only section"]);
    expect(snap.frontmatterKeys).toEqual(["title"]);
    expect(snap.managedBlockHash).toBe(
      computeMarkdownSnapshot("---\ntitle: bare\n---\n").managedBlockHash,
    );
  });

  // Heading-level filtering is what makes the body hash + section list
  // robust to formatting-only edits inside h1/h3/h4 chunks. A regression
  // loosening SECTION_RE to `^#+\s+` would drag h1/h3 changes into the
  // section list and fire false-positive drift on every replay diff.
  it("only captures ## headings; # and ### / #### are NOT sections", () => {
    const mixed = `# Top-level title\n## Real section\n### Subhead inside section\n## Another\n#### Deep heading\n`;
    expect(computeMarkdownSnapshot(mixed).sections).toEqual([
      "Real section",
      "Another",
    ]);
  });

  // Critical regression guard: every generated page has a managed fence
  // and the fence ITSELF carries a `## Generated by` boilerplate line in
  // some publisher templates. `sections` MUST exclude anything inside the
  // fence or the examples/ self-test (signal #2) would see drift on every
  // regen even when the body is byte-identical, and the replay diff would
  // count fence churn as section changes.
  it("excludes ## headings that live INSIDE the managed fence", () => {
    const fenced = `## Body section\n\nbody copy\n\n<!-- code2wiki:managed:start id=x -->\n## Generated metadata\n*Confidence: high.*\n<!-- code2wiki:managed:end -->\n`;
    expect(computeMarkdownSnapshot(fenced).sections).toEqual(["Body section"]);
  });

  // FENCE_RE has no /g flag, so .match returns ONLY the first hit and
  // .replace removes ONLY the first occurrence. Result: a second
  // fence-shaped block is treated as ordinary body content (its sections
  // surface in `sections`, its text contributes to `contentHash`). A
  // regression that adds /g to either would silently drop subsequent
  // fence content from the body hash and break replay drift detection
  // for any page where a stray fence comment lives in the body.
  it("treats only the FIRST managed fence as managed; later fence-shaped blocks stay in the body", () => {
    const twoFences = `## A\n<!-- code2wiki:managed:start -->\nFIRST\n<!-- code2wiki:managed:end -->\n## B\n<!-- code2wiki:managed:start -->\nSECOND\n<!-- code2wiki:managed:end -->\n## C\n`;
    const snap = computeMarkdownSnapshot(twoFences);
    expect(snap.sections).toEqual(["A", "B", "C"]);
    // managedBlockHash hashes ONLY the first fence body ("FIRST", trimmed)
    const firstOnly = `<!-- code2wiki:managed:start -->\nFIRST\n<!-- code2wiki:managed:end -->`;
    expect(snap.managedBlockHash).toBe(
      computeMarkdownSnapshot(firstOnly).managedBlockHash,
    );
  });

  // An empty fence (degenerate but possible; e.g., a stub created before
  // the first publish) must hash deterministically rather than crash or
  // emit an undefined-shaped value. Pinned to the well-known sha256("")
  // constant so a refactor that accidentally feeds `null` or
  // `parsed.content` into sha256() trips here instead of in production.
  it("hashes an empty managed fence as sha256 of the empty string", () => {
    const empty = `## H\nbody\n<!-- code2wiki:managed:start -->\n<!-- code2wiki:managed:end -->\n`;
    const SHA256_EMPTY =
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
    expect(computeMarkdownSnapshot(empty).managedBlockHash).toBe(SHA256_EMPTY);
  });

  // Sort is plain `Array.prototype.sort` over the gray-matter key set,
  // which is UTF-16 codepoint order; uppercase letters sort before
  // lowercase. A regression to `localeCompare` would silently swap
  // ordering for any page with mixed-case frontmatter and bust any
  // baseline.snapshot.json the examples/ self-test pins.
  it("sorts frontmatter keys by codepoint order (case-sensitive), not locale-aware", () => {
    const mixedCase = `---\nZebra: 1\napple: 2\nBanana: 3\n---\n`;
    expect(computeMarkdownSnapshot(mixedCase).frontmatterKeys).toEqual([
      "Banana",
      "Zebra",
      "apple",
    ]);
  });

  // Frontmatter-only input (no body at all) is what gray-matter produces
  // when the file is a stub. The body must hash to sha256("") AND
  // bodyLineCount must be 0; a regression returning 1 (treating "" as
  // a single empty line via "".split("\n")) would inflate the line count
  // and confuse drift reports.
  it("returns bodyLineCount=0 and empty-string hash for frontmatter-only input", () => {
    const stub = `---\ntitle: stub\n---\n`;
    const snap = computeMarkdownSnapshot(stub);
    expect(snap.bodyLineCount).toBe(0);
    expect(snap.contentHash).toBe(
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    );
    expect(snap.sections).toEqual([]);
  });

  // Bare body (no `---` block at all), gray-matter yields data={}, so
  // frontmatterKeys must be []. A regression that ever inserted a default
  // key here would shift the snapshot for every legacy hand-written .md
  // a customer adopts via `claim` mode.
  it("returns frontmatterKeys=[] when the input has no frontmatter block", () => {
    const bare = `## H\nbody\n`;
    expect(computeMarkdownSnapshot(bare).frontmatterKeys).toEqual([]);
  });

  // Section captures use the regex group `(.+?)\s*$`, so trailing
  // whitespace is stripped. The follow-up `.trim()` in code strips the
  // leading whitespace too. Pinning both halves so a regression dropping
  // either does NOT silently change section identity for a header like
  // `##  Spacey title  ` (which is the form a copy-paste from a wiki UI
  // often produces).
  it("trims leading and trailing whitespace from section titles", () => {
    const padded = `##   Spacey title   \nbody\n`;
    expect(computeMarkdownSnapshot(padded).sections).toEqual(["Spacey title"]);
  });
});
