import { describe, it, expect, vi } from "vitest";
import { ConfluencePublisher } from "../../src/core/publishers/confluence.js";
import type { PageInput } from "../../src/core/publishers/types.js";

/**
 * Operator-run scale + retry smoke for the Confluence publisher.
 *
 * Gated on CODE2WIKI_PUBLISHER_SMOKE_URL (+ matching email / token /
 * space-key env vars). The entire `describe` block skips cleanly when
 * the URL is unset, so regular `npm test` runs do NOT touch this file
 * and no live network calls fire from CI or developer machines.
 *
 * When the operator opts in, the suite exercises two surfaces:
 *
 *   1. Dry-run smoke: 50-page synthetic payload (ContentBox-flavoured
 *      content duplicated with deterministic slug suffixes) against
 *      the configured sandbox URL with dryRun=true. The Confluence
 *      publisher's dryRun path still issues READ requests (it looks
 *      up existing pages so it can report the correct outcome), but
 *      makes ZERO writes. We assert: every page resolves to a result
 *      with outcome in {created, updated} and the dry-run marker is
 *      present in the message. Failures here typically mean the
 *      sandbox is unreachable, auth is bad, or the space-key is wrong.
 *
 *   2. Simulated 429-storm against a mocked fetch: the 50-page payload
 *      runs through a fetch that returns 429 on the first call to
 *      every endpoint then 200 on the second. Asserts: every page
 *      still resolves successfully AND the call count proves the
 *      retry path fired (>=2 calls per page worth of requests). This
 *      half does NOT touch the real sandbox; the env var is the
 *      operator's signal to opt into the file's tests as a whole.
 *
 * Out of scope for this scaffold (operator follow-up, NOT bot work):
 *   - Timing measurements / SLO assertions (no perf budget defined).
 *   - "Corruption" determination, requires diffing the sandbox state
 *     before and after, against an expected baseline the operator owns.
 *   - Notion equivalent (parallel suite once a Notion sandbox is
 *     provisioned). Same publisher contract; copy this file once the
 *     NotionPublisher's dryRun path lands a similar fast path.
 */

const SMOKE_URL = process.env["CODE2WIKI_PUBLISHER_SMOKE_URL"];
const SMOKE_EMAIL = process.env["CODE2WIKI_PUBLISHER_SMOKE_EMAIL"];
const SMOKE_TOKEN = process.env["CODE2WIKI_PUBLISHER_SMOKE_TOKEN"];
const SMOKE_SPACE_KEY = process.env["CODE2WIKI_PUBLISHER_SMOKE_SPACE_KEY"];

// Single gate: the URL's presence opts the entire suite in. The other
// three vars are required when the gate fires; missing any of them
// throws inside the test so the operator sees a clear error.
const ENABLED = !!SMOKE_URL;

const PAGE_COUNT = 50;

/**
 * Synthetic page modelled after a ContentBox-style use case (CFML
 * module-level operation). Fields are stable strings so the test is
 * deterministic; only the suffix changes per page.
 */
function buildSyntheticPage(index: number): PageInput {
  const suffix = String(index + 1).padStart(3, "0");
  return {
    code2wiki_id: `cfml-contentbox-publisher-publishrelease-${suffix}-v1`,
    slug: `publish-a-content-release-${suffix}`,
    title: `Publish a content release ${suffix}`,
    tags: ["contentbox", "publishing", "modules"],
    markdown: [
      `## Summary`,
      ``,
      `An administrator promotes pending content edits to the live site for release ${suffix}. The system snapshots affected content rows, applies the new version, and invalidates the public cache.`,
      ``,
      `## Actor and triggers`,
      ``,
      `- **Actor:** Site administrator`,
      `- **Trigger:** POST /admin/publisher/release/${suffix} submitted from the publishing dashboard.`,
      ``,
      `## Main flow`,
      ``,
      `1. The administrator selects pending changes for release ${suffix}.`,
      `2. The system snapshots the affected content rows.`,
      `3. The new version is written and the prior version is marked superseded.`,
      `4. The public cache is invalidated for impacted URLs.`,
      `5. A notification is sent to the configured release channel.`,
      ``,
      `## Source links`,
      `<details>`,
      `<summary>Implementation files (for developers and auditors)</summary>`,
      ``,
      `- \`modules/contentbox/models/system/Publisher.cfc\` lines 240-310`,
      ``,
      `</details>`,
      ``,
      `<!-- code2wiki:managed:start id=cfml-contentbox-publisher-publishrelease-${suffix}-v1 -->`,
      `*Generated by code2wiki from commit \`abc1234\` on 2026-05-16T00:00:00Z.*`,
      `*Confidence: **medium***`,
      `<!-- code2wiki:managed:end -->`,
      ``,
    ].join("\n"),
  };
}

function buildSyntheticPayload(): PageInput[] {
  return Array.from({ length: PAGE_COUNT }, (_, i) => buildSyntheticPage(i));
}

describe.skipIf(!ENABLED)(
  "publisher-scale: 50-page Confluence dry-run smoke (live sandbox)",
  () => {
    it("publishes 50 synthetic pages in dry-run mode without writing", async () => {
      if (!SMOKE_EMAIL || !SMOKE_TOKEN || !SMOKE_SPACE_KEY) {
        throw new Error(
          "CODE2WIKI_PUBLISHER_SMOKE_URL is set but one of EMAIL / TOKEN / SPACE_KEY is missing. All four must be set together.",
        );
      }
      const publisher = new ConfluencePublisher(
        {
          baseUrl: SMOKE_URL!,
          email: SMOKE_EMAIL,
          apiToken: SMOKE_TOKEN,
          spaceKey: SMOKE_SPACE_KEY,
        },
        { dryRun: true },
      );

      const pages = buildSyntheticPayload();
      const results = await publisher.publish(pages);

      // One result per input page (no silent drops).
      expect(results).toHaveLength(PAGE_COUNT);
      for (const r of results) {
        // dryRun guarantees no writes; outcome is the result of a
        // read-only existence check, so "created" (page absent) or
        // "updated" (page present) are the only legal states. A
        // regression that flipped dryRun into a real-publish path
        // would show "skipped" (collision in claim mode) or "error"
        // entries here.
        expect(["created", "updated"]).toContain(r.outcome);
        expect(r.message).toBeDefined();
        expect(r.message).toMatch(/dry run/i);
      }
    }, 180_000); // 3-minute ceiling: 50 sequential read calls × ~1s each + slack.
  },
);

describe.skipIf(!ENABLED)(
  "publisher-scale: 429-retry storm under load (mocked fetch, no live network)",
  () => {
    it("retries on 429 and completes all 50 pages when the upstream recovers", async () => {
      // Mock fetch that returns 429 on the first call to each unique URL,
      // then 200 with a minimal valid body on the second. Mirrors a
      // burst hitting the per-endpoint rate limiter on Atlassian:
      // first hit gets throttled, retry succeeds.
      const seen = new Set<string>();
      const fetchImpl = vi.fn(async (input: RequestInfo | URL) => {
        const url = typeof input === "string" ? input : input.toString();
        if (!seen.has(url)) {
          seen.add(url);
          // Retry-After: 0 keeps the test instant; the retry helper's
          // computeDelayMs will still floor it through Math.min and
          // sleep for 0ms. The retry-helper unit tests pin the actual
          // jitter math; this test pins the integration shape.
          return new Response("", {
            status: 429,
            headers: { "Retry-After": "0" },
          });
        }
        // Minimal "no existing page" search response, drives the
        // dryRun branch's read path to report outcome="created".
        return new Response(JSON.stringify({ results: [] }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      });

      const publisher = new ConfluencePublisher(
        {
          baseUrl: SMOKE_URL!,
          email: SMOKE_EMAIL ?? "test@example.com",
          apiToken: SMOKE_TOKEN ?? "test-token",
          spaceKey: SMOKE_SPACE_KEY ?? "TEST",
        },
        {
          dryRun: true,
          fetch: fetchImpl as unknown as typeof fetch,
          // Tight retry budget so an unexpected pile-up surfaces fast
          // rather than burning the 10s test timeout.
          retry: { maxAttempts: 3, sleep: async () => {} },
        },
      );

      const pages = buildSyntheticPayload();
      const results = await publisher.publish(pages);

      // Every page must resolve to a real result, no silent drops
      // even when every first attempt got a 429.
      expect(results).toHaveLength(PAGE_COUNT);
      for (const r of results) {
        expect(r.outcome).toBe("created");
      }

      // Fetch was called MORE than once per page (the retry fired on
      // the first hit to each unique URL). Lower bound: 2 × pages.
      // Exact count depends on how many unique URLs the dryRun path
      // touches per page (currently 1 search per page), so use >=.
      expect(fetchImpl.mock.calls.length).toBeGreaterThanOrEqual(
        PAGE_COUNT * 2,
      );
    });
  },
);
