import yaml from "js-yaml";
import type { UseCase } from "./types.js";

/**
 * Render a UseCase as Markdown matching docs/usecase-template.md, with the
 * code2wiki-managed fence so human edits outside the fence survive
 * regeneration.
 *
 * @param useCase the use case to render
 * @param validSlugs optional set of slug values that exist in this run.
 *        When provided, related-use-cases links are only emitted for slugs
 *        in the set; others are rendered as plain text. This prevents broken
 *        anchors when the LLM speculates about related pages that weren't
 *        actually generated.
 */
export function renderUseCase(
  useCase: UseCase,
  validSlugs?: Set<string>,
): string {
  const frontmatter = yaml.dump(
    {
      code2wiki_id: useCase.code2wiki_id,
      title: useCase.title,
      slug: useCase.slug,
      actor: useCase.actor,
      status: useCase.status,
      last_generated: useCase.last_generated,
      last_commit: useCase.last_commit,
      confidence: useCase.confidence,
      source_files: useCase.source_files,
      tags: useCase.tags,
    },
    { lineWidth: -1, noRefs: true },
  );

  const sections: string[] = [];

  sections.push("## Summary");
  sections.push(useCase.summary);

  sections.push("## Actor and triggers");
  sections.push(`- **Actor:** ${useCase.actor}`);
  if (useCase.trigger) {
    sections.push(`- **Trigger:** ${useCase.trigger}`);
  }

  if (useCase.preconditions.length) {
    sections.push("## Preconditions");
    sections.push(useCase.preconditions.map((p) => `- ${p}`).join("\n"));
  }

  if (useCase.main_flow.length) {
    sections.push("## Main flow");
    const numbered = useCase.main_flow
      .map((s, i) => {
        const note = s.footnote ? ` [^step${i + 1}]` : "";
        return `${i + 1}. ${s.step}${note}`;
      })
      .join("\n");
    sections.push(numbered);
    const footnotes = useCase.main_flow
      .map((s, i) => (s.footnote ? `[^step${i + 1}]: ${s.footnote}` : null))
      .filter(Boolean)
      .join("\n");
    if (footnotes) sections.push(footnotes);
  }

  if (useCase.alternate_flows.length) {
    sections.push("## Alternate and exception flows");
    sections.push(
      useCase.alternate_flows
        .map((a) => `- **${a.label}:** ${a.description}`)
        .join("\n"),
    );
  }

  if (useCase.postconditions.length) {
    sections.push("## Postconditions");
    sections.push(useCase.postconditions.map((p) => `- ${p}`).join("\n"));
  }

  if (useCase.business_rules.length) {
    sections.push("## Business rules");
    const rules = useCase.business_rules
      .map((r, i) => {
        const note = r.footnote ? ` [^rule${i + 1}]` : "";
        return `- ${r.rule}${note}`;
      })
      .join("\n");
    sections.push(rules);
    const ruleNotes = useCase.business_rules
      .map((r, i) => (r.footnote ? `[^rule${i + 1}]: ${r.footnote}` : null))
      .filter(Boolean)
      .join("\n");
    if (ruleNotes) sections.push(ruleNotes);
  }

  if (useCase.test_scenarios.length) {
    sections.push("## Suggested test scenarios");
    sections.push(
      useCase.test_scenarios
        .map((t) => `- **${t.label}**: ${t.gwt}`)
        .join("\n"),
    );
  }

  if (useCase.related.length) {
    sections.push("## Related use cases");
    sections.push(
      useCase.related
        .map((r) => {
          // If validSlugs is provided, only emit a link if the slug is in
          // the set; otherwise emit plain text. This prevents broken anchors
          // when the LLM speculates about related pages that weren't
          // generated in this run.
          if (validSlugs && !validSlugs.has(r.slug)) {
            return `- ${r.title}`;
          }
          return `- [${r.title}](${r.slug})`;
        })
        .join("\n"),
    );
  }

  sections.push("## Source links");
  sections.push("<details>");
  sections.push(
    "<summary>Implementation files (for developers and auditors)</summary>",
  );
  sections.push("");
  sections.push(
    useCase.source_files
      .map((s) => `- \`${s.path}\` lines ${s.lines}`)
      .join("\n"),
  );
  sections.push("");
  sections.push("</details>");

  const body = sections.join("\n\n");

  return [
    "---",
    frontmatter.trimEnd(),
    "---",
    "",
    body,
    "",
    "---",
    "",
    `<!-- code2wiki:managed:start id=${useCase.code2wiki_id} -->`,
    `*Generated by [code2wiki](https://github.com/aqlong/code2wiki) from commit \`${useCase.last_commit}\` on ${useCase.last_generated}.*`,
    `*Confidence: **${useCase.confidence}**${
      useCase.confidence_reason ? `, ${useCase.confidence_reason}` : ""
    }*`,
    `<!-- code2wiki:managed:end -->`,
    "",
  ].join("\n");
}
