import { describe, it, expect } from "vitest";
import { buildSummary } from "./pr-summary.mjs";

const generate = (page, outcome, source) => ({
  timestamp: "2026-05-08T12:00:00.000Z",
  operation: "generate",
  commit: "abc123",
  page,
  outcome,
  details: { source },
  content_hash: "sha256:abc",
  prev_hash: null,
  entry_hash: "sha256:def",
});

const publish = (page, outcome, target, url) => ({
  timestamp: "2026-05-08T12:01:00.000Z",
  operation: "publish",
  commit: "abc123",
  page,
  outcome,
  details: { target, url, mode: "claim" },
  content_hash: "sha256:abc",
  prev_hash: null,
  entry_hash: "sha256:def",
});

const claim = (page, target, externalId, placement = "below") => ({
  timestamp: "2026-05-08T12:00:30.000Z",
  operation: "claim",
  commit: "abc123",
  page,
  outcome: "updated",
  details: { target, external_id: externalId, placement },
  content_hash: null,
  prev_hash: null,
  entry_hash: "sha256:def",
});

describe("buildSummary", () => {
  it("returns a friendly placeholder when there are no entries", () => {
    const md = buildSummary([]);
    expect(md).toContain("📝 code2wiki");
    expect(md).toMatch(/No audit-log entries/);
  });

  it("counts generate outcomes correctly", () => {
    const entries = [
      generate("a", "created", "src/a.cfc"),
      generate("b", "created", "src/b.cfc"),
      generate("c", "updated", "src/c.cfc"),
      generate("d", "unchanged", "src/d.cfc"),
    ];
    const md = buildSummary(entries);
    expect(md).toMatch(/Generated docs:\*\* 2 created · 1 updated · 1 unchanged · 0 error/);
    expect(md).toContain("✨ Created (2)");
    expect(md).toContain("🔄 Updated (1)");
    expect(md).toContain("·  Unchanged (1)");
    // The errored section is omitted when there are no errors.
    expect(md).not.toContain("⚠  Errored");
  });

  it("includes per-page details inside collapsed sections", () => {
    const entries = [generate("foo-bar", "created", "src/foo.java")];
    const md = buildSummary(entries);
    expect(md).toContain("`foo-bar`");
    expect(md).toContain("(src/foo.java)");
    expect(md).toContain("<details><summary>");
  });

  it("renders publish entries with target + URL", () => {
    const entries = [
      publish("foo", "created", "confluence", "https://wiki.example/foo"),
      publish("bar", "updated", "notion", "https://notion.so/bar"),
    ];
    const md = buildSummary(entries);
    expect(md).toMatch(/Published to wiki:\*\* 1 created · 1 updated/);
    expect(md).toContain("`foo` → confluence https://wiki.example/foo");
    expect(md).toContain("`bar` → notion https://notion.so/bar");
  });

  it("renders claim entries with target + page id + placement", () => {
    const entries = [claim("foo-bar", "confluence", "12345", "above")];
    const md = buildSummary(entries);
    expect(md).toContain("Pages adopted (claim):** 1");
    expect(md).toContain("🤝 `foo-bar` ← confluence:12345 (placement=above)");
  });

  it("counts skipped publish entries as errors", () => {
    const entries = [publish("foo", "skipped", "confluence", undefined)];
    const md = buildSummary(entries);
    expect(md).toMatch(/0 created · 0 updated · 1 skipped/);
  });

  it("filters by --since timestamp", () => {
    const entries = [
      { ...generate("old", "created", "x"), timestamp: "2026-05-07T10:00:00.000Z" },
      { ...generate("new", "created", "y"), timestamp: "2026-05-08T13:00:00.000Z" },
    ];
    const md = buildSummary(entries, { since: "2026-05-08T12:00:00.000Z" });
    expect(md).toContain("`new`");
    expect(md).not.toContain("`old`");
    expect(md).toMatch(/1 created/);
  });

  it("ends with a code2wiki attribution footer", () => {
    const md = buildSummary([generate("a", "created", "x")]);
    expect(md).toMatch(/Generated by \[code2wiki\]/);
  });
});
