#!/usr/bin/env node
//
// Build a Markdown summary of code2wiki audit-log entries written during
// a single workflow run. Used by .github/workflows/code2wiki.yml to post
// a sticky PR comment + a job-summary block in the Actions tab.
//
// Usage:
//   node tools/pr-summary.mjs                        # summarise the whole audit log
//   node tools/pr-summary.mjs --since 2026-05-08T12:00:00Z
//   node tools/pr-summary.mjs --audit path/to/audit.jsonl
//
// Output: Markdown on stdout. Exit code 0 always; if the log is missing,
// emits a helpful "no entries" placeholder so the workflow can still
// post something readable.
import fs from "node:fs/promises";
import path from "node:path";

function parseArgs(argv) {
  const args = { since: null, audit: null };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--since" && argv[i + 1]) {
      args.since = argv[++i];
    } else if (a === "--audit" && argv[i + 1]) {
      args.audit = argv[++i];
    } else if (a === "-h" || a === "--help") {
      process.stdout.write(
        "Usage: node tools/pr-summary.mjs [--since <ISO>] [--audit <path>]\n",
      );
      process.exit(0);
    }
  }
  return args;
}

async function readEntries(auditPath) {
  let raw;
  try {
    raw = await fs.readFile(auditPath, "utf-8");
  } catch (e) {
    if (e.code === "ENOENT") return [];
    throw e;
  }
  const entries = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      entries.push(JSON.parse(line));
    } catch {
      // Tolerate a corrupted line so the workflow still posts something.
    }
  }
  return entries;
}

/** Build the Markdown summary. Exported for tests. */
export function buildSummary(entries, opts = {}) {
  const since = opts.since ? new Date(opts.since).getTime() : null;
  const filtered = since
    ? entries.filter((e) => {
        const t = Date.parse(e.timestamp ?? "");
        return Number.isFinite(t) && t >= since;
      })
    : entries.slice();

  const generates = filtered.filter((e) => e.operation === "generate");
  const publishes = filtered.filter((e) => e.operation === "publish");
  const claims = filtered.filter((e) => e.operation === "claim");

  const lines = [];
  lines.push("## 📝 code2wiki, use-case doc changes");
  lines.push("");

  if (!filtered.length) {
    lines.push(
      "_No audit-log entries from this run._ This usually means no source files changed (diff-aware regen had nothing to do).",
    );
    lines.push("");
    lines.push(
      "<sub>Generated by [code2wiki](https://github.com/aqlong/code2wiki), preview before merge.</sub>",
    );
    return lines.join("\n");
  }

  // Generate summary.
  if (generates.length) {
    const counts = countByOutcome(generates);
    lines.push(
      `**Generated docs:** ${counts.created} created · ${counts.updated} updated · ${counts.unchanged} unchanged · ${counts.error} error(s)`,
    );
    lines.push("");
    appendOutcomeList(lines, generates, "created", "✨ Created");
    appendOutcomeList(lines, generates, "updated", "🔄 Updated");
    appendOutcomeList(lines, generates, "unchanged", "·  Unchanged");
    appendOutcomeList(lines, generates, "error", "⚠  Errored");
  }

  if (publishes.length) {
    const counts = countByOutcome(publishes);
    lines.push("");
    lines.push(
      `**Published to wiki:** ${counts.created} created · ${counts.updated} updated · ${counts.error} skipped`,
    );
    lines.push("");
    for (const e of publishes) {
      const sym = symbolFor(e.outcome);
      const target = e.details?.target ? ` → ${e.details.target}` : "";
      const url = e.details?.url ? ` ${e.details.url}` : "";
      lines.push(`- ${sym} \`${e.page}\`${target}${url}`);
    }
  }

  if (claims.length) {
    lines.push("");
    lines.push(`**Pages adopted (claim):** ${claims.length}`);
    lines.push("");
    for (const e of claims) {
      const target = e.details?.target ?? "?";
      const ext = e.details?.external_id ?? "?";
      const placement = e.details?.placement ?? "below";
      lines.push(
        `- 🤝 \`${e.page}\` ← ${target}:${ext} (placement=${placement})`,
      );
    }
  }

  lines.push("");
  lines.push(
    "<sub>Generated by [code2wiki](https://github.com/aqlong/code2wiki). Preview before merge, these counts reflect what will publish to your Confluence/Notion space on the next run.</sub>",
  );
  return lines.join("\n");
}

function countByOutcome(entries) {
  const c = { created: 0, updated: 0, unchanged: 0, error: 0 };
  for (const e of entries) {
    if (c[e.outcome] != null) c[e.outcome] += 1;
    else if (e.outcome === "skipped") c.error += 1;
  }
  return c;
}

function appendOutcomeList(lines, entries, outcome, header) {
  const matches = entries.filter((e) => e.outcome === outcome);
  if (!matches.length) return;
  lines.push(`<details><summary>${header} (${matches.length})</summary>`);
  lines.push("");
  for (const e of matches) {
    const src = e.details?.source ? ` _(${e.details.source})_` : "";
    lines.push(`- \`${e.page}\`${src}`);
  }
  lines.push("");
  lines.push("</details>");
}

function symbolFor(outcome) {
  switch (outcome) {
    case "created":
      return "✨";
    case "updated":
      return "🔄";
    case "unchanged":
      return "·";
    case "skipped":
    case "error":
      return "⚠";
    default:
      return "?";
  }
}

// CLI entry point, only runs when invoked directly, not when imported by tests.
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs(process.argv);
  const auditPath =
    args.audit ?? path.resolve(process.cwd(), ".code2wiki", "audit.jsonl");
  const entries = await readEntries(auditPath);
  const md = buildSummary(entries, { since: args.since });
  process.stdout.write(md + "\n");
}
