import { describe, it, expect } from "vitest";
import {
  bannerPlainText,
  buildConfluenceBanner,
  buildNotionBannerBlock,
  resolveBannerInputs,
  extractManagedRegion,
  extractOutsideManagedRegion,
  type BannerInputs,
} from "./types.js";

const FIXED_NOW = "2026-05-07T12:00:00.000Z";
const INPUTS: BannerInputs = {
  repoName: "acme-monolith",
  sourceLink: "https://github.com/acme/monolith/commit/deadbeef",
  lastSyncedIso: FIXED_NOW,
};

describe("banner copy invariants (BN-4 / BN-5 / BN-11)", () => {
  it("starts with the canonical 📝 prefix", () => {
    const text = bannerPlainText(INPUTS);
    expect(text.startsWith("📝 **This page is auto-generated by code2wiki**")).toBe(true);
  });

  it("ends with a 'Last synced: <ISO-8601>' marker", () => {
    const text = bannerPlainText(INPUTS);
    expect(text).toMatch(/Last synced: 2026-05-07T12:00:00\.000Z/);
  });

  it("includes the source link", () => {
    expect(bannerPlainText(INPUTS)).toContain(INPUTS.sourceLink);
  });

  it("BN-5: stays ≤ 500 chars", () => {
    expect(bannerPlainText(INPUTS).length).toBeLessThanOrEqual(500);
  });

  it("BN-11: timestamp is UTC ISO-8601", () => {
    expect(INPUTS.lastSyncedIso).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
    expect(INPUTS.lastSyncedIso.endsWith("Z")).toBe(true);
  });
});

describe("Confluence banner block (BN-1)", () => {
  it("renders an info-macro structured-macro block", () => {
    const xml = buildConfluenceBanner(INPUTS);
    expect(xml.startsWith('<ac:structured-macro ac:name="info"')).toBe(true);
    expect(xml).toContain("acme-monolith");
    expect(xml).toContain("View source");
    expect(xml).toContain("📝");
  });

  it("escapes XML in the repo name", () => {
    const xml = buildConfluenceBanner({
      ...INPUTS,
      repoName: '<script>alert("x")</script>',
    });
    expect(xml).not.toContain("<script>");
    expect(xml).toContain("&lt;script&gt;");
  });
});

describe("Notion banner block (BN-2)", () => {
  it("is a callout with the 📝 emoji", () => {
    const block = buildNotionBannerBlock(INPUTS) as {
      type: string;
      callout: { icon: { type: string; emoji: string }; rich_text: unknown[] };
    };
    expect(block.type).toBe("callout");
    expect(block.callout.icon.emoji).toBe("📝");
    expect(Array.isArray(block.callout.rich_text)).toBe(true);
  });
});

describe("BN-6 / BN-7: source link selection", () => {
  it("uses commit permalink when commitUrlTemplate + commit are present", () => {
    const inputs = resolveBannerInputs(
      {
        banner: {
          repoName: "acme",
          repoUrl: "https://github.com/acme/x",
          commitUrlTemplate: "https://github.com/acme/x/commit/{commit}",
          commit: "abc1234",
          now: () => FIXED_NOW,
        },
      },
      { repoName: "fallback", commit: "abc1234" },
    );
    expect(inputs.sourceLink).toBe("https://github.com/acme/x/commit/abc1234");
  });

  it("falls back to repo URL when commit hash is unavailable", () => {
    const inputs = resolveBannerInputs(
      {
        banner: {
          repoName: "acme",
          repoUrl: "https://github.com/acme/x",
          commitUrlTemplate: "https://github.com/acme/x/commit/{commit}",
          commit: undefined,
          now: () => FIXED_NOW,
        },
      },
      { repoName: "fallback" },
    );
    expect(inputs.sourceLink).toBe("https://github.com/acme/x");
  });
});

describe("BN-8: managed-region extraction does not include the banner", () => {
  it("treats banner as outside the fence", () => {
    const xml = `${buildConfluenceBanner(INPUTS)}\n<!-- code2wiki:managed:start id=foo -->\n<p>generated</p>\n<!-- code2wiki:managed:end -->`;
    const inside = extractManagedRegion(xml);
    expect(inside).toContain("<p>generated</p>");
    expect(inside).not.toContain("ac:structured-macro");
    expect(inside).not.toContain("📝");
  });
});

describe("extractOutsideManagedRegion", () => {
  it("splits before/after correctly", () => {
    const text = `BANNER\n<!-- code2wiki:managed:start id=foo -->\nINSIDE\n<!-- code2wiki:managed:end -->\nORIGINAL_BELOW`;
    const { before, after } = extractOutsideManagedRegion(text);
    expect(before.trim()).toBe("BANNER");
    expect(after.trim()).toBe("ORIGINAL_BELOW");
  });

  it("treats text without a fence as fully outside", () => {
    const { before, after } = extractOutsideManagedRegion("plain content");
    expect(before).toBe("plain content");
    expect(after).toBe("");
  });
});

// extractManagedRegion + extractOutsideManagedRegion are the load-bearing
// fence-arithmetic helpers every publish/republish flow consults. Both
// have FOUR branches (no-open / open-but-malformed / open-but-unterminated
// / full-fence), but only the no-fence and full-fence branches were
// directly pinned above. The two malformed-fence branches matter:
//
//   - On extractManagedRegion both malformed branches return null, but a
//     regression that returned an empty string or the post-`-->` slice
//     would silently re-publish a "blank" managed page and erase a
//     customer's claim-time content.
//   - On extractOutsideManagedRegion the two malformed branches have
//     DIFFERENT semantics. open-without-`-->` returns the full text
//     as `before`, while open-with-`-->`-without-close returns
//     `text.slice(0, start)`. A regression collapsing them would either
//     drop a fence-open marker the customer hand-wrote (case A) or
//     silently swallow content past a half-broken fence (case B).
//
// Plus: extractManagedRegion is `.trim()`'d (whitespace inside the
// fence is normalized) but extractOutsideManagedRegion preserves
// `after` verbatim (customer post-fence content must round-trip).
// And both use `indexOf` (first-occurrence), so multi-fence input
// picks the FIRST fence; a regression to `lastIndexOf` would
// silently invert semantics for any text with two fence-like
// comments (e.g., a page that documents the fence syntax inline).
describe("extractManagedRegion: malformed and multi-fence branches", () => {
  it("returns null when the text has no FENCE_OPEN_PREFIX at all", () => {
    expect(extractManagedRegion("plain content with no fence")).toBeNull();
    expect(extractManagedRegion("")).toBeNull();
  });

  it("returns null when the open comment is missing its `-->` closer (malformed fence open)", () => {
    // The open prefix is present but the `-->` that terminates the HTML
    // comment never appears. Returning anything other than null here
    // would mean treating malformed HTML as a valid fence; at minimum
    // a publisher diff would silently classify a half-typed comment as
    // managed.
    const text = "<!-- code2wiki:managed:start id=foo\nINSIDE\nORIGINAL";
    expect(extractManagedRegion(text)).toBeNull();
  });

  it("returns null when the fence is opened but never closed (no FENCE_CLOSE marker)", () => {
    // Open marker is complete but the corresponding end marker is
    // missing. Returning the post-`-->` slice would silently surface
    // the customer's pre-claim hand-written content as "managed" and
    // then overwrite it on the next publish.
    const text = "<!-- code2wiki:managed:start id=foo -->\nINSIDE\nNO_END_MARKER";
    expect(extractManagedRegion(text)).toBeNull();
  });

  it("trims leading and trailing whitespace inside the fence (normalization invariant)", () => {
    // Both publishers normalize the inside-fence body via .trim() so
    // the rendered managed region doesn't drift across re-publishes
    // due to incidental indentation changes. A regression dropping
    // the .trim() would surface as a perpetually-dirty managed-region
    // diff on every republish.
    const text =
      "<!-- code2wiki:managed:start id=foo -->\n\n   <p>generated</p>\n\n  <!-- code2wiki:managed:end -->";
    expect(extractManagedRegion(text)).toBe("<p>generated</p>");
  });

  it("picks the FIRST fence when the text contains two (indexOf semantic, not lastIndexOf)", () => {
    // Multiple fence-like comments in the same document (e.g., a
    // user-facing page that quotes our own fence syntax inline) must
    // resolve to the FIRST complete fence's inner body. A regression
    // to lastIndexOf would silently invert which body the publisher
    // treats as managed on every re-publish for the customer who
    // documents code2wiki's own fence syntax.
    const text =
      "<!-- code2wiki:managed:start id=foo -->FIRST<!-- code2wiki:managed:end -->BETWEEN<!-- code2wiki:managed:start id=bar -->SECOND<!-- code2wiki:managed:end -->";
    expect(extractManagedRegion(text)).toBe("FIRST");
  });
});

describe("extractOutsideManagedRegion: malformed-fence branches diverge intentionally", () => {
  it("returns full text as `before` (and empty `after`) when the open marker has no `-->` closer", () => {
    // The open prefix is present but the `-->` that would terminate
    // the HTML comment never appears. The function treats this as
    // "no usable fence found", same as the no-fence path: the entire
    // text becomes `before`, and `after` is empty. A regression that
    // collapsed this branch with the next one would silently drop the
    // customer's fence-open marker from the preserved-outside content.
    const text = "BEFORE\n<!-- code2wiki:managed:start id=foo\nDANGLING";
    const { before, after } = extractOutsideManagedRegion(text);
    expect(before).toBe(text);
    expect(after).toBe("");
  });

  it("returns text-up-to-open as `before` (and empty `after`) when the fence is open + commented but never closed", () => {
    // Open marker is complete (`-->` present) but the corresponding
    // end marker is missing. The function chops `before` at the open
    // marker's start (strict asymmetry vs the previous case): here
    // the customer's intent was clearly to fence SOMETHING, even if
    // the end marker is missing, so the publisher trusts `before` as
    // pre-fence content. A regression collapsing this with the
    // previous case would silently surface the half-typed fence
    // body as preservable content on the next publish.
    const text = "BEFORE\n<!-- code2wiki:managed:start id=foo -->\nINSIDE_NO_END";
    const { before, after } = extractOutsideManagedRegion(text);
    expect(before).toBe("BEFORE\n");
    expect(after).toBe("");
  });

  it("preserves `after` verbatim with no trim or normalization (customer trailing content round-trips)", () => {
    // The claim flow writes [banner][fence-managed][hr][customer's
    // pre-claim original] and trusts mergePreservedOutside to put the
    // customer's trailing chunk back on every republish. If that
    // chunk's leading or trailing whitespace were silently trimmed,
    // hand-written content with intentional vertical spacing
    // (markdown blank-line paragraphs, code-block padding) would
    // drift on every publish. Pin no-trim on the `after` half.
    const text =
      "<!-- code2wiki:managed:start id=foo -->INSIDE<!-- code2wiki:managed:end -->\n\n  PRESERVED  \n\n";
    const { after } = extractOutsideManagedRegion(text);
    expect(after).toBe("\n\n  PRESERVED  \n\n");
  });
});

describe("escapeXml ordering (via buildConfluenceBanner)", () => {
  // Regression pin: ampersand MUST be the first replacement; otherwise
  // replace(/</) → &lt;, then replace(/&/) → &amp; would double-escape
  // into &amp;lt; and corrupt every Confluence storage publish.
  it("escapes & before < > \" so all four survive without double-escape", () => {
    const xml = buildConfluenceBanner({ ...INPUTS, repoName: '& and "<>"' });
    expect(xml).toContain('&amp; and &quot;&lt;&gt;&quot;');
    expect(xml).not.toContain("&amp;lt;");
    expect(xml).not.toContain("&amp;amp;");
  });
});

describe("buildConfluenceBanner sourceLink XML escape (BN-1 hazard)", () => {
  // sourceLink is interpolated into href="...", a raw `&` or `"` would
  // break Confluence storage parse silently on every publish.
  it("escapes both & and \" inside the href so the storage XML stays well-formed", () => {
    const xml = buildConfluenceBanner({
      ...INPUTS,
      sourceLink: 'https://example.com/repo?a=1&b="x"',
    });
    expect(xml).toContain("a=1&amp;b=&quot;x&quot;");
    expect(xml).toMatch(/href="https:\/\/example\.com\/repo\?a=1&amp;b=&quot;x&quot;"/);
  });
});

describe("buildNotionBannerBlock rich_text shape (BN-2)", () => {
  // Pins the 4-element layout, bold title, body, View-source-with-link,
  // period. A regression rearranging or collapsing these would surface
  // live as a broken Notion banner with no test feedback.
  it("emits 4 rich_text segments with the link URL plumbed through", () => {
    const block = buildNotionBannerBlock(INPUTS) as {
      callout: {
        rich_text: Array<{
          text: { content: string; link?: { url: string } };
          annotations?: { bold: boolean };
        }>;
      };
    };
    const rt = block.callout.rich_text;
    expect(rt).toHaveLength(4);
    expect(rt[0].annotations).toEqual({ bold: true });
    expect(rt[0].text.content).toBe("This page is auto-generated by code2wiki");
    expect(rt[1].text.content).toContain("acme-monolith");
    expect(rt[1].text.content).toContain("Last synced");
    expect(rt[2].text.content).toBe("View source");
    expect(rt[2].text.link?.url).toBe(INPUTS.sourceLink);
    expect(rt[3].text.content).toBe(".");
  });
});

describe("resolveBannerInputs edge branches (BN-6 / BN-7)", () => {
  it("undefined cfg uses defaults.repoName + invalid-placeholder sourceLink", () => {
    const inputs = resolveBannerInputs(undefined, { repoName: "fallback-repo" });
    expect(inputs.repoName).toBe("fallback-repo");
    expect(inputs.sourceLink).toBe("https://example.invalid/fallback-repo");
    expect(inputs.lastSyncedIso).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
  });

  // Load-bearing: git-derived commit can be "unknown" for first-publish-from-a-
  // non-git-checkout. A regression that dropped this guard would emit a
  // /.../commit/unknown URL, a dead link on every page.
  it('commit="unknown" is treated as missing, falls back to repoUrl', () => {
    const inputs = resolveBannerInputs(
      {
        banner: {
          commitUrlTemplate: "https://github.com/acme/x/commit/{commit}",
          commit: "unknown",
          repoUrl: "https://github.com/acme/x",
          now: () => FIXED_NOW,
        },
      },
      { repoName: "fallback" },
    );
    expect(inputs.sourceLink).toBe("https://github.com/acme/x");
  });

  it("repoUrl-only banner (no commitUrlTemplate) uses repoUrl directly", () => {
    const inputs = resolveBannerInputs(
      { banner: { repoUrl: "https://github.com/acme/x", now: () => FIXED_NOW } },
      { repoName: "fallback" },
    );
    expect(inputs.sourceLink).toBe("https://github.com/acme/x");
  });

  it("banner.now omitted produces a real ISO-8601 UTC timestamp", () => {
    const inputs = resolveBannerInputs(
      { banner: { repoUrl: "https://x.test" } },
      { repoName: "r" },
    );
    expect(inputs.lastSyncedIso).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
    expect(inputs.lastSyncedIso.endsWith("Z")).toBe(true);
  });

  it("no repoUrl + no commitUrlTemplate falls back to invalid-placeholder URL", () => {
    const inputs = resolveBannerInputs(
      { banner: { repoName: "only-name", now: () => FIXED_NOW } },
      { repoName: "default" },
    );
    expect(inputs.sourceLink).toBe("https://example.invalid/only-name");
  });

  // defaults.commit must flow when banner.commit is omitted, this is how
  // the publisher passes the git-HEAD commit into the URL template without
  // requiring the config file to know the hash.
  it("defaults.commit flows into the template when banner.commit is omitted", () => {
    const inputs = resolveBannerInputs(
      {
        banner: {
          commitUrlTemplate: "https://github.com/acme/x/commit/{commit}",
          now: () => FIXED_NOW,
        },
      },
      { repoName: "r", commit: "feedbeef" },
    );
    expect(inputs.sourceLink).toBe("https://github.com/acme/x/commit/feedbeef");
  });
});

describe("extractManagedRegion null-paths", () => {
  it("returns null when there is no fence at all", () => {
    expect(extractManagedRegion("plain content with no fence")).toBeNull();
  });

  it("returns null when the open marker is missing its `-->` close", () => {
    const text = "before <!-- code2wiki:managed:start id=foo no arrow more text";
    expect(extractManagedRegion(text)).toBeNull();
  });

  it("returns null when no close marker follows the open", () => {
    const text =
      "<!-- code2wiki:managed:start id=foo --> inside but no close marker";
    expect(extractManagedRegion(text)).toBeNull();
  });

  // Pins the .trim() at the end of extractManagedRegion, without it, every
  // fenced body would carry surrounding whitespace and inflate publish diffs.
  it("trims leading/trailing whitespace from the extracted body", () => {
    const text =
      "<!-- code2wiki:managed:start id=foo -->\n  body  \n<!-- code2wiki:managed:end -->";
    expect(extractManagedRegion(text)).toBe("body");
  });
});

describe("extractOutsideManagedRegion malformed-fence paths", () => {
  it("open marker without `-->` treats the whole text as `before`", () => {
    const text = "BANNER <!-- code2wiki:managed:start id=foo trailing text";
    const { before, after } = extractOutsideManagedRegion(text);
    expect(before).toBe(text);
    expect(after).toBe("");
  });

  it("open + arrow + no close → before is text up to start, after is empty", () => {
    const text =
      "BANNER\n<!-- code2wiki:managed:start id=foo --> inside but no close";
    const { before, after } = extractOutsideManagedRegion(text);
    expect(before).toBe("BANNER\n");
    expect(after).toBe("");
  });
});
