import { describe, expect, it } from "vitest";
import { transformFootnotes } from "./footnotes.js";

describe("transformFootnotes", () => {
  it("is a no-op when the input has no footnote tokens", () => {
    const input = "# Title\n\nJust plain text.\n";
    expect(transformFootnotes(input)).toBe(input);
  });

  it("renumbers refs to sequential integers in first-mention order", () => {
    const input = [
      "First reference [^bravo] then second [^alpha] then bravo again [^bravo].",
      "[^alpha]: A def",
      "[^bravo]: B def",
    ].join("\n");
    const out = transformFootnotes(input);
    // bravo appears first → [1], alpha second → [2]
    expect(out).toContain("First reference [1] then second [2] then bravo again [1].");
  });

  it("strips definition lines from their original location", () => {
    const input = [
      "Some text [^x].",
      "[^x]: definition body",
      "More text.",
    ].join("\n");
    const out = transformFootnotes(input);
    expect(out).not.toContain("[^x]:");
    expect(out).toContain("Some text [1].");
    expect(out).toContain("More text.");
  });

  it("appends a Footnotes section in number order at the end", () => {
    const input = [
      "Para [^a] and [^b].",
      "[^a]: alpha",
      "[^b]: bravo",
    ].join("\n");
    const out = transformFootnotes(input);
    expect(out).toMatch(/## Footnotes\n+1\. alpha\n2\. bravo\n$/);
  });

  it("keeps dangling references unchanged (no matching definition)", () => {
    const input = "Mentions [^unknown] but defines [^known].\n[^known]: real";
    const out = transformFootnotes(input);
    // [^unknown] stays literal because there's no def to attach a number to.
    expect(out).toContain("[^unknown]");
    expect(out).toContain("[1]"); // known got number 1
  });

  it("includes orphan definitions (defined, never referenced) at the bottom", () => {
    const input = "No references here.\n[^orphan]: still defined";
    const out = transformFootnotes(input);
    expect(out).toContain("## Footnotes");
    expect(out).toContain("1. still defined");
  });

  it("preserves the body's original line structure (paragraphs, lists)", () => {
    const input = [
      "# Title",
      "",
      "Para one [^a].",
      "",
      "- bullet [^b]",
      "- another",
      "",
      "[^a]: alpha def",
      "[^b]: bravo def",
    ].join("\n");
    const out = transformFootnotes(input);
    // Heading and bullets preserved.
    expect(out).toContain("# Title");
    expect(out).toMatch(/- bullet \[2\]/);
    expect(out).toMatch(/- another/);
  });

  it("handles ids with letters, digits, underscores, and hyphens", () => {
    const input = "Ref [^step_1] and [^rule-2a].\n[^step_1]: a\n[^rule-2a]: b";
    const out = transformFootnotes(input);
    expect(out).toContain("Ref [1] and [2].");
    expect(out).toContain("1. a");
    expect(out).toContain("2. b");
  });

  it("is idempotent on input that contains no footnote refs and has Footnotes section pre-rendered", () => {
    const input = "Body.\n\n## Footnotes\n\n1. existing\n";
    // No `[^...]` tokens, so transform should leave it as-is.
    expect(transformFootnotes(input)).toBe(input);
  });

  it("is a no-op when refs are present but no definitions are (all-orphan refs)", () => {
    // Pins the `defContent.size === 0` short-circuit. A regression dropping
    // that early return would fall into the rewrite path and emit a
    // `## Footnotes` section with zero entries, producing an empty section
    // header at the end of every page that uses ref syntax without defs.
    const input = "First ref [^a] then [^b] and a third [^c].\n";
    expect(transformFootnotes(input)).toBe(input);
  });

  it("last-write-wins on duplicate definition ids (Pandoc parity)", () => {
    // Pins the documented "last-write-wins on duplicate ids" contract at
    // footnotes.ts:46. A regression flipping to first-write-wins or
    // throw-on-duplicate would silently change what BAs see in published
    // pages when the LLM emits two `[^x]:` lines (rare but observed).
    const input = [
      "Reference [^x] once.",
      "[^x]: first definition",
      "[^x]: second definition",
    ].join("\n");
    const out = transformFootnotes(input);
    expect(out).toContain("1. second definition");
    expect(out).not.toContain("first definition");
  });

  it("inserts the Footnotes section before the trailing managed fence, not after it", () => {
    // Pins the fence-aware placement. renderer.ts emits the
    // `<!-- code2wiki:managed:start … -->` attribution fence LAST, separated
    // from the body by a `---`. Appending footnotes at the absolute string
    // end would push the list below the "Generated by code2wiki / Confidence"
    // footer in every published Confluence + Notion page. The section must
    // land in the body, before the `---` separator that precedes the fence.
    const input = [
      "## Main flow",
      "",
      "1. Validate input [^step1]",
      "[^step1]: Lines 5-9",
      "",
      "---",
      "",
      "<!-- code2wiki:managed:start id=uc-1 -->",
      "*Generated by code2wiki from commit `abc` on 2026-05-29.*",
      "<!-- code2wiki:managed:end -->",
      "",
    ].join("\n");
    const out = transformFootnotes(input);
    const footnotesIdx = out.indexOf("## Footnotes");
    const fenceStartIdx = out.indexOf("<!-- code2wiki:managed:start");
    const separatorIdx = out.lastIndexOf("\n---\n");
    expect(footnotesIdx).toBeGreaterThan(-1);
    // Footnotes come before BOTH the `---` separator and the fence footer.
    expect(footnotesIdx).toBeLessThan(separatorIdx);
    expect(footnotesIdx).toBeLessThan(fenceStartIdx);
    // The fence itself is preserved intact (Confluence relies on it).
    expect(out).toContain("<!-- code2wiki:managed:start id=uc-1 -->");
    expect(out).toContain("<!-- code2wiki:managed:end -->");
    expect(out).toContain("1. Lines 5-9");
    // Body ref renumbered, definition line stripped from its original spot.
    expect(out).toContain("1. Validate input [1]");
    expect(out).not.toContain("[^step1]:");
  });

  it("falls back to end-append when no managed fence is present", () => {
    // Guards that the fence-aware branch does not change fence-less output:
    // CLI preview and raw-body callers still get the section at the very end.
    const input = "Body [^a].\n[^a]: alpha";
    const out = transformFootnotes(input);
    expect(out).toMatch(/^Body \[1\]\.\n\n## Footnotes\n\n1\. alpha\n$/);
  });

  it("strips trailing blank lines from the body before the Footnotes section", () => {
    // Pins lines 86-88 (the body-trim loop). A regression dropping the
    // trim would yield 4+ blank lines between body and `## Footnotes` on
    // every page with a footnoted final paragraph (LLM emits a trailing
    // blank after the last body line), shifting BA-edit-back inlineDiffSize
    // and degrading the calibrator's noise floor.
    const input = [
      "Para [^a].",
      "",
      "",
      "",
      "[^a]: alpha",
    ].join("\n");
    const out = transformFootnotes(input);
    // Body line is followed by exactly one blank line (two consecutive \n)
    // before `## Footnotes`. Three trailing blanks in the input were stripped;
    // without the trim, four-plus consecutive \n would land between body and
    // heading on every page with a footnoted final paragraph.
    expect(out).toMatch(/^Para \[1\]\.\n\n## Footnotes\n\n1\. alpha\n$/);
  });

  it("places footnotes directly before a fence with no preceding `---`, not at an earlier body `---`", () => {
    // Pins the fence-placement fallback (footnotes.ts lines 99-106). The
    // backward scan that locates the `---` separator must stop at the first
    // non-blank line before the fence. When that line is NOT a separator
    // (the renderer normally emits one, but CLI preview / hand-authored
    // fragments may not), footerStartIdx stays at the fence line and the
    // footnotes land directly above it. A regression that kept scanning back
    // for ANY `---` would anchor on an unrelated horizontal-rule earlier in
    // the body and hoist the footnote list into the middle of the page.
    const input = [
      "## Section A",
      "Content [^a].",
      "[^a]: note alpha",
      "",
      "---",
      "",
      "## Section B",
      "More content",
      "",
      "<!-- code2wiki:managed:start id=uc-1 -->",
      "*Generated by code2wiki from commit `abc` on 2026-05-29.*",
      "<!-- code2wiki:managed:end -->",
      "",
    ].join("\n");
    const out = transformFootnotes(input);
    const bodyRuleIdx = out.indexOf("\n---\n");
    const moreContentIdx = out.indexOf("More content");
    const footnotesIdx = out.indexOf("## Footnotes");
    const fenceStartIdx = out.indexOf("<!-- code2wiki:managed:start");
    // The footnote section sits AFTER the last body content and the body's
    // own horizontal rule, and BEFORE the attribution fence.
    expect(bodyRuleIdx).toBeGreaterThan(-1);
    expect(footnotesIdx).toBeGreaterThan(bodyRuleIdx);
    expect(footnotesIdx).toBeGreaterThan(moreContentIdx);
    expect(footnotesIdx).toBeLessThan(fenceStartIdx);
    // Fence preserved; ref renumbered; definition line stripped.
    expect(out).toContain("<!-- code2wiki:managed:start id=uc-1 -->");
    expect(out).toContain("<!-- code2wiki:managed:end -->");
    expect(out).toContain("Content [1].");
    expect(out).toContain("1. note alpha");
    expect(out).not.toContain("[^a]:");
  });
});
